import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The docs sidebar is fully AUTOGENERATED from the docs/ folder tree, so the
 * left nav mirrors the folder structure 1:1. Content authors control ordering
 * and labels with:
 *   - _category_.json   (per folder: label, position, link, collapsed)
 *   - frontmatter       (per file: sidebar_position, sidebar_label, title)
 *
 * There is nothing to edit in this file when adding/removing/reordering docs.
 * The key here ("docsSidebar") must match `sidebarId` in docusaurus.config.ts.
 */
const sidebars: SidebarsConfig = {
  // The docs root (/docs/) is a GENERATED INDEX — an auto-built list of the
  // sections below — rather than a single markdown file. This is durable: the
  // docs/ folder is regenerated from upstream on every build (scripts/sync-docs.sh),
  // so we don't rely on any specific file (like README.md) landing at the root.
  // README.md still ships as a normal page; sync-docs.sh gives it a slug so it
  // no longer claims the /docs/ route.
  docsSidebar: [
    {
      type: 'category',
      label: 'Documentation',
      link: {
        type: 'generated-index',
        title: 'Rossoctl Documentation',
        description:
          'Guides, concepts, and references for deploying and operating Rossoctl.',
        slug: '/',
      },
      items: [{type: 'autogenerated', dirName: '.'}],
    },
  ],
};

export default sidebars;
