import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The docs sidebar is fully AUTOGENERATED from the docs/ folder tree, so the
 * left nav mirrors the folder structure 1:1. Content authors control ordering
 * and labels with:
 *   - _category_.json   (per folder: label, position, link, collapsed)
 *   - frontmatter       (per file: sidebar_position, sidebar_label, title)
 *
 * There is nothing to edit in this file when adding/removing/reordering docs.
 * The key here ("docsSidebar") must match `sidebarId` in docusaurus.config.ts.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
