import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar for the standalone "Contributing" docs instance (see the second
 * plugin-content-docs entry in docusaurus.config.ts). Autogenerated from the
 * contributing/ folder, so it grows automatically if more contributor pages
 * are added (code of conduct, dev setup, etc.).
 */
const sidebars: SidebarsConfig = {
  contributingSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
